### ISSUE TITLE
A simple roadmap to a better mathquill

### ISSUE THREAD

**Issue by LeoDog896** [desmosinc/mathquill#244]
I'm not sure if something like this already exists internally, but as most of the people reading this probably know, the current state of the mathquill codebase is quite a mess. Thus, I think a simple TODO list could help us get this project to easier maintenance speed.

Note: I do think that a new release of MathQuill should probably be breaking to reduce any legacy backwards code (with a migration guide, of course)

TODO:
- [x] Get all tests working (they seem to be broken at the moment)
- [ ] Port all tests to typescript to avoid catchable runtime errors
- [ ] Remove JQuery entirely
- [ ] Remove extra code in outro.js (part 1/3 for ES Module port)
- [ ] Implement eslint to force code restrictions (notably avoiding window.* and setting global variables w/ var * ignoring MathQuill) (avoid bleeding side effects for part 2/3)
- [ ] export MathQuill and associated variables (and entirely remove vars) (part 3/3)
- [ ] Remove circular dependencies
- [ ] Use a build tool such as esbuild (we may have to force file order at first)

And with that, MathQuill will be a proper module, which should allow it to connect to faster tooling, giving everyone involved a better developer experience.

If the upstream still can't be merged, it would be safe to assume that desmos should publish an NPM package for MathQuill.

I'm personally fine with doing the rest, but the tests completely broke and its quite a nightmare -- ill see what I can do about it.
